# Version management for TinyVU
# This file centralizes version information

file(READ "${CMAKE_SOURCE_DIR}/VERSION" TINYVU_VERSION_STRING)
string(STRIP "${TINYVU_VERSION_STRING}" TINYVU_VERSION_STRING)

string(REGEX MATCH "^([0-9]+)\\.([0-9]+)\\.([0-9]+)(-(.+))?$" VERSION_MATCH "${TINYVU_VERSION_STRING}")

if(VERSION_MATCH)
    set(TINYVU_VERSION_MAJOR ${CMAKE_MATCH_1})
    set(TINYVU_VERSION_MINOR ${CMAKE_MATCH_2})
    set(TINYVU_VERSION_PATCH ${CMAKE_MATCH_3})

    if(CMAKE_MATCH_5)
        set(TINYVU_VERSION_SUFFIX ${CMAKE_MATCH_5})
        set(TINYVU_VERSION_FULL "${TINYVU_VERSION_MAJOR}.${TINYVU_VERSION_MINOR}.${TINYVU_VERSION_PATCH}-${TINYVU_VERSION_SUFFIX}")
    else()
        set(TINYVU_VERSION_SUFFIX "")
        set(TINYVU_VERSION_FULL "${TINYVU_VERSION_MAJOR}.${TINYVU_VERSION_MINOR}.${TINYVU_VERSION_PATCH}")
    endif()
else()
    message(FATAL_ERROR "Invalid version format in VERSION file: ${TINYVU_VERSION_STRING}")
endif()

set(PROJECT_VERSION "${TINYVU_VERSION_MAJOR}.${TINYVU_VERSION_MINOR}.${TINYVU_VERSION_PATCH}")
set(PROJECT_VERSION_MAJOR ${TINYVU_VERSION_MAJOR})
set(PROJECT_VERSION_MINOR ${TINYVU_VERSION_MINOR})
set(PROJECT_VERSION_PATCH ${TINYVU_VERSION_PATCH})

if(NOT CMAKE_CURRENT_SOURCE_DIR STREQUAL CMAKE_SOURCE_DIR)
    set(TINYVU_VERSION ${TINYVU_VERSION_FULL} PARENT_SCOPE)
endif()

message(STATUS "TinyVU Version: ${TINYVU_VERSION_FULL}")
message(STATUS "  Major: ${TINYVU_VERSION_MAJOR}")
message(STATUS "  Minor: ${TINYVU_VERSION_MINOR}")
message(STATUS "  Patch: ${TINYVU_VERSION_PATCH}")
if(TINYVU_VERSION_SUFFIX)
    message(STATUS "  Suffix: ${TINYVU_VERSION_SUFFIX}")
endif()
